/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package proyecto1_enero2021;

import java.util.Random;

/**
 *
 * @author leonl
 */
public class Generador extends java.awt.Frame {

   
    /**
     * Creates new form Generador
     */
    public Generador() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        Revision revision= new Revision();
        
        Random rand= new Random(System.currentTimeMillis());
        int num_hilos= 10;
        Thread hilos[] = new Thread[num_hilos];
        
        for(int i=0; i<num_hilos; i++){
            int num_alea= rand.nextInt(10);
            if(num_alea<=6){
                Teoria t= new Teoria(i+1, revision);
                hilos[i]= t;
            }else{
               Practicas p= new Practicas(i+1, revision);
               Thread pr= new Thread(p);
               hilos[i]= pr;
            }
            hilos[i].start();
        }
        
        for (int i = 0; i < num_hilos; i++) {
            hilos[i].join();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
