
import static java.lang.Thread.sleep;
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

/**
 *Generador, que lanza 30 hilos entre uno y 2 segundos, tiene que
 * lanzar 75% gente de la derecha y 25%de la izquierda
 * @author Lucia Zamudio
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generador().setVisible(true);
            }
        });*/
        int ancho=800;
        int alto=800;
        Generador g= new Generador();
        
        g.setTitle("Pasarela");
        
        Canva cv= new Canva(ancho,alto);
        Pasarela ps = new Pasarela();
        cv.setPasarela(ps);
        ps.setCanvas(cv);
        
        g.add(cv);
        g.setSize(ancho,alto);
        g.setLocationRelativeTo(null);
        g.setVisible(true);
        
        int num_hilos=30;
        Thread[] hilos = new Thread[num_hilos];
        for(int i=0; i<num_hilos; i++){
            Random rand= new Random(System.currentTimeMillis());
            int numAlea= rand.nextInt(100);
            if(numAlea<=75){
                Derecha der = new Derecha(ps,i+1);
                hilos[i]=der;
            }else{
                Izquierda izq= new Izquierda(ps,i+1);
                Thread iz= new Thread(izq);
                hilos[i]=iz;
            }
            sleep(rand.nextInt(1000)+1000);
            hilos[i].start();
        }
        for(int i=0; i<num_hilos;i++){
            hilos[i].join();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
