/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package enero2021_proyecto3;

import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

/**
 *
 * @author leonl
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form Generadoe
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException, ExecutionException {
        Revision revision= new Revision();
        Random rand= new Random(System.currentTimeMillis());
        
        ExecutorService ex_practicas = Executors.newFixedThreadPool(5);
        ArrayList<Future<Long>> resultados= new ArrayList<>();
        
        int num_hilos= 10;
        Thread hilos[] = new Thread[num_hilos];
        
        for(int i=0; i<num_hilos; i++){
            int num_alea= rand.nextInt(10);
            if(num_alea<=6){
                Teoria t= new Teoria(i+1, revision);
                hilos[i]= t;
                hilos[i].start();
            }else{
               Practica p= new Practica(i+1, revision);
               Future f= ex_practicas.submit(p);
               resultados.add(f);
            }
            
        }   
        for (int i = 0; i < num_hilos; i++) {
            if(hilos[i]==null){
                continue;
            }
            hilos[i].join();
        }
        
        long t_total=0;
        for (Future<Long> f : resultados){
            t_total+= f.get();
        }
        
        System.out.println("El tiempo total es: "+ t_total);
        
        ex_practicas.shutdown();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
