/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package Interfaz;

import java.util.Random;
import pcd_p5.Combustion;
import pcd_p5.Electrico;
import pcd_p5.Parking;

/**
 *
 * @author Lucía Zamudio
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form NewFrame
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        int alto = 600;
        int ancho = 900;

        Generador f = new Generador();

        f.setTitle("Parking");
        f.setSize(ancho, alto);
        
        f.setLocationRelativeTo(null);

        Canva cv = new Canva(ancho, alto);
        f.add(cv);
        Parking parking = new Parking();
        cv.setParking(parking);
        parking.setCanvas(cv);
        
        f.setVisible(true);

        
        Random rand = new Random(System.nanoTime());
        int num_hilos=30;
        
        Thread[] hilos = new Thread[num_hilos];
        for(int i=0; i<num_hilos;i++){
            int id=i+1;
            int num_alea= rand.nextInt(2);
            if(num_alea==0){
                Electrico e = new Electrico(id, parking);   
                hilos[i]=e;
                hilos[i].start();
            }else{
                Combustion com= new Combustion(id,parking);
                Thread c= new Thread(com);
                hilos[i]=c;
                hilos[i].start();
                
            }           
            Thread.sleep(rand.nextInt(1000)+1000);
        }
        
        for(int i=0; i<num_hilos; i++){
            hilos[i].join();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
