/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package Interfaz;

import java.util.Random;
import pcd_p6.Camion;
import pcd_p6.Generador;
import pcd_p6.Tractor;



/**
 *
 * @author Lucía Zamudio
 */
public class Frame extends java.awt.Frame {
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        int ancho=1024;
        int alto =764;
        
        Frame f=new Frame();
        f.setTitle("Cooperativa");
        f.setSize(ancho, alto);
        f.setLocationRelativeTo(null);
        
        Canva cv = new Canva(ancho, alto);
        Generador gen = new Generador(cv);
        
        cv.setGenerador(gen);
        
        f.add(cv);
        f.setVisible(true);
        
        Random rand = new Random(System.nanoTime());
        int num_hilos = 20;
        Thread hilos[] = new Thread[num_hilos];
        for (int i = 0; i < num_hilos; i++) {
            int num_alea = rand.nextInt(10);
            if (num_alea < 7) {
                Camion c = new Camion(i+1, gen, cv);
                gen.addVehiculoEspera(c);

                hilos[i] = c;
            } else {
                Tractor tr = new Tractor(i+1, gen, cv);
                Thread t = new Thread(tr);
                gen.addVehiculoEspera(tr);

                hilos[i] = t;
            }
            hilos[i].start();
            try {
                Thread.sleep(rand.nextInt(1000) + 1000);
            } catch (InterruptedException ex) {
                System.getLogger(Frame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }

        for (int i = 0; i < num_hilos; i++) {
            try {
                hilos[i].join();
            } catch (InterruptedException ex) {
                System.getLogger(Frame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
